(() => {
  const API="https://api.escoreboards.eu/api/club-registry"; const $=s=>document.querySelector(s); let key=""; let club=null;
  const msg=(el,t)=>{el.textContent=t||"";el.hidden=!t};
  async function req(path,opt={}){const headers={...(opt.headers||{})}; if(!(opt.body instanceof FormData))headers["Content-Type"]="application/json"; const r=await fetch(API+path,{...opt,headers}); let b=null;try{b=await r.json()}catch{} if(!r.ok)throw new Error(b?.detail||`Request failed (${r.status})`);return b}
  function render(){ $("#clubHeading").textContent=club.name; $("#clubPath").textContent=club.publicPath; $("#editName").value=club.name||""; $("#editAddress").value=club.address||""; $("#deletePhrase").textContent=`DELETE ${club.name}`; const logo=$("#currentLogo"); if(club.logo){logo.src=club.logo;logo.hidden=false}else logo.hidden=true; const host=$("#courtEditor");host.innerHTML=""; for(const c of club.courts){const row=document.createElement("div");row.className="court-row";row.dataset.id=c.id;row.innerHTML=`<div class="court-index">${c.id.replace('court-','')}</div><input value="${String(c.name).replaceAll('&','&amp;').replaceAll('"','&quot;')}"><select><option value="tennis">Tennis</option><option value="padel">Padel</option><option value="pickleball">Pickleball</option></select>`;row.querySelector('select').value=c.sport;row.querySelector('input').addEventListener('change',()=>saveCourt(row));row.querySelector('select').addEventListener('change',()=>saveCourt(row));host.appendChild(row)}}
  async function reload(){const b=await req('/member/club',{method:'POST',body:JSON.stringify({clubKey:key})});club=b.club;render()}
  async function saveCourt(row){try{msg($("#courtMsg"),"");await req('/member/court',{method:'PATCH',headers:{'X-Club-Key':key},body:JSON.stringify({courtId:row.dataset.id,name:row.querySelector('input').value.trim(),sport:row.querySelector('select').value})});msg($("#courtMsg"),'Court saved.')}catch(e){msg($("#courtMsg"),e.message)}}
  $("#loginForm").addEventListener('submit',async e=>{e.preventDefault();msg($("#loginMsg"),"");key=$("#clubKeyInput").value.trim();try{await reload();$("#loginCard").hidden=true;$("#manageCard").hidden=false}catch(err){msg($("#loginMsg"),err.message)}});
  $("#saveClub").addEventListener('click',async()=>{try{msg($("#saveMsg"),"");await req('/member/club',{method:'PATCH',headers:{'X-Club-Key':key},body:JSON.stringify({name:$("#editName").value.trim(),address:$("#editAddress").value.trim()})});const f=$("#editLogo").files?.[0];if(f){const fd=new FormData();fd.append('logo',f);await req('/member/logo',{method:'POST',headers:{'X-Club-Key':key},body:fd})}await reload();msg($("#saveMsg"),'Saved.')}catch(e){msg($("#saveMsg"),e.message)}});
  $("#deleteClub").addEventListener('click',async()=>{if(!club)return;try{msg($("#deleteMsg"),"");const b=await req('/member/delete',{method:'POST',headers:{'X-Club-Key':key},body:JSON.stringify({confirm:$("#deleteConfirm").value})});alert('Club removed from the VoxCourt registry.');location.href='./'}catch(e){msg($("#deleteMsg"),e.message)}});
})();
